

ALTER TABLE LR1.dbo.Company ADD 
	CONSTRAINT PK_C PRIMARY KEY(CompanyID),
	CONSTRAINT UK_C UNIQUE(CompanyID)
GO 

ALTER TABLE LR1.dbo.FilmDirector ADD 
	CONSTRAINT PK_FD PRIMARY KEY(FilmDirectorID),
	CONSTRAINT UK_FD UNIQUE(FilmDirectorID)
GO 

ALTER TABLE LR1.dbo.Film ADD 
	CONSTRAINT PK_F PRIMARY KEY(FilmID),
	CONSTRAINT UK_F UNIQUE(FilmID)
GO 

ALTER TABLE LR1.dbo.Film_Actor ADD 
	CONSTRAINT PK_FA PRIMARY KEY(Film_ActorID),
	CONSTRAINT UK_FA UNIQUE(Film_ActorID)
GO

ALTER TABLE LR1.dbo.Actor ADD 
	CONSTRAINT PK_A PRIMARY KEY(ActorID),
	CONSTRAINT UK_AA UNIQUE(ActorID)
GO

ALTER TABLE LR1.dbo.Genre ADD 
	CONSTRAINT PK_G PRIMARY KEY(GenreID),
	CONSTRAINT UK_G UNIQUE(GenreID)
GO

ALTER TABLE LR1.dbo.Film ADD
	CONSTRAINT F_FDID FOREIGN KEY(FilmDirectorID) REFERENCES LR1.dbo.FilmDirector(FilmDirectorID),
    CONSTRAINT F_CID FOREIGN KEY(CompanyID) REFERENCES LR1.dbo.Company(CompanyID),
	CONSTRAINT F_GID FOREIGN KEY(GenreID) REFERENCES LR1.dbo.Genre(GenreID)
GO

ALTER TABLE LR1.dbo.Film_Actor ADD
	--CONSTRAINT F_FID FOREIGN KEY(FilmID) REFERENCES LR1.dbo.Film(FilmID),
    CONSTRAINT F_AID FOREIGN KEY(ActorID) REFERENCES LR1.dbo.Actor(ActorID)
GO