

ALTER TABLE CS.dbo.Contracts ADD 
	CONSTRAINT PK_Contracts PRIMARY KEY(id),
	CONSTRAINT UK_Contracts UNIQUE(id)
GO 

ALTER TABLE CS.dbo.Person ADD 
	CONSTRAINT PK_Person PRIMARY KEY(id),
	CONSTRAINT UK_Person UNIQUE(id)
GO 

ALTER TABLE CS.dbo.Serviec ADD 
	CONSTRAINT PK_Serviec PRIMARY KEY(id),
	CONSTRAINT UK_Serviec UNIQUE(id)
GO

ALTER TABLE CS.dbo.Car ADD 
	CONSTRAINT PK_Car PRIMARY KEY(id),
	CONSTRAINT UK_Car UNIQUE(id)
GO 

ALTER TABLE CS.dbo.ModelCar ADD 
	CONSTRAINT PK_ModelCar PRIMARY KEY(id),
	CONSTRAINT UK_ModelCar UNIQUE(id)
GO

ALTER TABLE CS.dbo.Contracts ADD
	CONSTRAINT FK_id_car FOREIGN KEY(id_car) REFERENCES Car(id),
    CONSTRAINT FK_id_person FOREIGN KEY(id_person) REFERENCES CS.dbo.Person(id),
	CONSTRAINT FK_id_service FOREIGN KEY(id_service) REFERENCES CS.dbo.Serviec(id)
GO

ALTER TABLE CS.dbo.Car ADD
    CONSTRAINT FK_id_cmodel FOREIGN KEY(id_cmodel) REFERENCES CS.dbo.ModelCar(id)
GO